## Creating 1-D array


In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a.shape

(5,)

In [11]:
a.shape = (2,3)    #reshape array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b = np.array([7,9,7,5,4,3,2,1,5])
b

array([7, 9, 7, 5, 4, 3, 2, 1, 5])

In [13]:
b.reshape(3,3)    #reshape array

array([[7, 9, 7],
       [5, 4, 3],
       [2, 1, 5]])

In [14]:
b.shape

(9,)

## Creating 2-D array

In [15]:
array = np.array([[34,53,3,2],[23,45,22,53]])
array

array([[34, 53,  3,  2],
       [23, 45, 22, 53]])

In [16]:
array.shape

(2, 4)

In [17]:
array.reshape(4,2)

array([[34, 53],
       [ 3,  2],
       [23, 45],
       [22, 53]])

## range of numbers

In [18]:
aray = np.arange(24)
aray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
aray.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
aray.reshape(2,3,4)      #3-D array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
araay = np.arange(100)
araay

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
araay.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
araay.reshape(5,2,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [33]:
a = np.arange(10)
b = np.arange(11,21)
a+b


array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [34]:
a * b

array([  0,  12,  26,  42,  60,  80, 102, 126, 152, 180])

In [36]:
a/b

array([0.        , 0.08333333, 0.15384615, 0.21428571, 0.26666667,
       0.3125    , 0.35294118, 0.38888889, 0.42105263, 0.45      ])

In [41]:
(a-b)

array([-11, -11, -11, -11, -11, -11, -11, -11, -11, -11])

## Statistics of array

In [3]:
array = np.arange(12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
med = np.median(array)
med

5.5

In [7]:
arr = np.linspace(-2,2,2001)
arr

array([-2.   , -1.998, -1.996, ...,  1.996,  1.998,  2.   ])

In [12]:
std = np.std(arr)
std

1.1552777443829976

## Identity and Zeros matrices

In [13]:
i = np.ones(10)    #1-D 
i

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
ii = np.ones([5,5])
ii

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
ii = np.eye(5)
ii

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
zz = np.zeros([4,5])
zz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

## Flatten
    - to make 1-D from multi-D array

In [28]:
arr = np.array([[4,5],[7,6]])
arr

array([[4, 5],
       [7, 6]])

In [30]:
f = arr.flatten()
f

array([4, 5, 7, 6])

In [31]:
aarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
f = aarr.flatten()
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Transpose

In [40]:
aarr2 = aarr.transpose()
aarr2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
np.concatenate((aarr,aarr2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])